### ISSUE TITLE
Add to macOS System Preferences

### ISSUE THREAD

**Issue by cseelus** [ther0n/UnnaturalScrollWheels#1]
Would it be possible to add a System component, so that UnnaturalScrollWheels shows up in the System Preferences?

Also see https://news.ycombinator.com/item?id=23966571

**Comment by ther0n** [comment]
I think it is possible technically, I would have preferred to implement it this way as well. Currently the app works by intercepting scroll events, determining if they came from a mouse, inverting the input event data or modifying it to disable acceleration depending on settings, then passing it on to the application/system. With a preference pane I would need to have two pieces, a background process that does what I describe, and the preference pane. It addition to making it more complicated to develop (I only have 72 hours of macOS development), it would also be a little more complicated to install and require many more permissions.

Originally I was going to release on the App Store but decided against it due to the $100 a year fee to join the developer program, and the 30% fee Apple charges on paid apps making it harder to break even on that $100 a year. Still I want to keep the option open to release on the App Store open. Apps on the App Store need to be sandboxed and that means no preference pane.

**Comment by cseelus** [comment]
I see, thank for the extensive answer.

**Comment by jellevdvliet** [comment]
Hi @ther0n 
I am a member of the developer program. If you want you can contact me and I'd gladly work something out with you to get it in the App Store.

**Comment by ther0n** [comment]
Hi @jellevdvliet, thanks for the offer but seeing so much interest is making me re-evaluate paying the $100 to publish the app myself. I'll keep it in mind though!
