### ISSUE TITLE
does not work on macOS Big Sur

### ISSUE THREAD

**Issue by psprogis** [ther0n/UnnaturalScrollWheels#30]
![image](https://user-images.githubusercontent.com/7395225/136538557-0d10d3a4-7ca7-4831-8cb2-5e08aca6079d.png)

**Comment by luckman212** [comment]
Duplicate

- [UnnaturalScrollWheels can't be opened because Apple cannot check it for malicious software · Issue #27 · ther0n/UnnaturalScrollWheels](https://github.com/ther0n/UnnaturalScrollWheels/issues/27)
- [Cannot open in Big Sur 11.6 · Issue #29 · ther0n/UnnaturalScrollWheels](https://github.com/ther0n/UnnaturalScrollWheels/issues/29)
