### ISSUE TITLE
"Disable mouse acceleration" Not working in latest mac os/ipad os beta with universal control

### ISSUE THREAD

**Issue by onion9156** [ther0n/UnnaturalScrollWheels#41]
When moving the cursor from my Macbook to the iPad using apple's newest universal control feature in 12.3 Beta（21E5196i）
Universal control works as expected with default settings from mac os, however when using "disable mouse acceleration", the cursor moves to the iPad yet is stuck on the edge forever. The cursor appears on the mac screen and iPad screen simultaneously.
Cursor movements are not working, but scroll wheel and clicks are working as expected.
It seems that the transition caused the cursor to be stuck.
All software is on the newest version as of 31/1.

**Comment by onion9156** [comment]
WIth the terminal command "defaults write .GlobalPreferences com.apple.mouse.scaling -1"
I was able to turn off mouse acceleration AND have universal control both working perfectly as expected.

**Comment by cistearns** [comment]
I found that once you restart to make the terminal command take effect Universal Control stops reading the mouse as before. I suspect the issue is that as part of universal control it is trying to match the scaling value, and when it gets a value that is 'no acceleration' it breaks. So unless Apple does a better job of officially supporting non-acceleration it may be a situation of one or the other but not both. It is probably worth filing a bug with Apple, but since disabling acceleration isn't a normally exposed feature I don't expect we will get much traction.

**Comment by onion9156** [comment]
I have observed the same effects, with no fixes unfortunately.

**Comment by ther0n** [comment]
Unfortunately I don’t think this is possible to fix. macOS is forwarding the inputs from the mouse directly from macOS to iPadOS so macOS (and my app) can’t modify the scroll event variables (if they’re there at all when using iPadOS.)  The only way this could work is if apps were allowed to modify mouse variables; apps aren’t able to go out of the sandbox without a jailbreak to do things like that. And that’s after considering that the app wouldn’t be allowed on the AppStore in the first place. I would put this app on the macOS AppStore if I could. But since it modifies core functionality it wouldn’t be allowed.

The app should work fine with sidecar though!

**Comment by cistearns** [comment]
It would probably be worth adding a warning when enabling the "Disable Acceleration" about this incompatibility.
