### ISSUE TITLE
Disabling "Show menu bar icon" leaves an empty box in the menu bar.

### ISSUE THREAD

**Issue by marat-turaev** [ther0n/UnnaturalScrollWheels#8]
Disabling "Show menu bar icon" leaves a transparent box in the menu bar, see video:
https://user-images.githubusercontent.com/666822/102958247-5744b780-4491-11eb-9a01-1150b6b1b946.mov

Big Sur 11.1;
app v1.1.0

**Comment by ther0n** [comment]
Currently the menu bar icon hides itself by setting it's icon width to 0px. Seemed like kind of a hack when I first built the app, but it worked on Catalina and it was the only method I was able to find when searching around online. I will investigate what the proper method is for hiding menu bar icons at some point in the future (hopefully sooner rather than later).

**Comment by ther0n** [comment]
Actually just looked into the issue a bit myself, a work around for now is to click on another icon in the menu bar which will make the box disappear. When I have the menu bar icon hidden when running the app, I don't see any boxes appearing so this isn't a major issue in my opinion. I'm not sure if this is an issue with the app, or a bug in Big Sur. Most other apps with menu bar icons have the option to disable the menu bar in a separate preferences panel, not built directly into the dropdown menu on the menu bar.

**Comment by ther0n** [comment]
This is fixed in [1.2.0](https://github.com/ther0n/UnnaturalScrollWheels/releases/tag/1.2.0).
