### ISSUE TITLE
Broken on Ventura

### ISSUE THREAD

**Issue by adamency** [ther0n/UnnaturalScrollWheels#91]
Just wanted to let people know that this program which has not received any update for 2 years now, is not working anymore on modern versions of macOS.

I recommend using [Mos](https://github.com/Caldis/Mos) instead ([english readme here](https://github.com/Caldis/Mos/blob/master/README.enUS.md)) which I have personally tested sucessfully and can be installed simply via `brew install mos`.

**Comment by adamency** [comment]
Here are FYI other alternatives, which I have NOT tested:

https://github.com/pilotmoon/Scroll-Reverser
https://github.com/emreyolcu/discrete-scroll
https://github.com/linearmouse/linearmouse
https://github.com/noah-nuebling/mac-mouse-fix

**Comment by Gordi90** [comment]
Mos wasn't starting on Sequoia. Scroll-Reverser worked like a charm.

**Comment by ther0n** [comment]
Closing this issue as I know for a fact the app is working up to at least Sonoma 14.7 as I use it everyday and used Ventura everyday until recently. There is something else on your system that is interfering (do you have logitech or other mouse control software installed?). Without more information there's no way for me to fix whatever issue you are having. Solutions here also worked for some people: https://github.com/ther0n/UnnaturalScrollWheels/issues/67

**Comment by adamency** [comment]
I didn't have anything else installed on my macs pertaining to this. This is a fresh mac I had just received when I made this issue. I strictly install my programs with `brew` only, and your program was one of the very first packages I installed on it, besides other CLI-only programs which obviously cannot have any interactions with this.

**Comment by ther0n** [comment]
For anyone who comes across this in the future: in addition to other apps interferring theres also some sort of bug either with macOS or the app that I haven't been able to figure out that seems to happen randomly. Following the instructions here has always fixed it for me. Somehow (either a mistake in my permissions code, or due to macOS bugs) the accessiblity settings of macOS itself seems to be getting confused and is failing to give the app needed access.

https://github.com/ther0n/UnnaturalScrollWheels/issues/67#issuecomment-1371397494
